tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: common_gen_preference_model
  args:
    device: "cpu"
    batch_size: 5
    model_type: "11b"

  # values:
  #   - id: rouge_combined
  #   - id: meteor
  #   - id: rouge
  #     args:
  #       rouge_type: "rouge1"
  #   - id: spider
  #     args:
  #       spice_coeff: 0.0
  #       cider_coeff: 1.0
  #   - id: spider
  #     args:
  #       spice_coeff: 1.0
  #       cider_coeff: 0.0
  #   - id: spider
  #     args:
  #       spice_coeff: 0.5
  #       cider_coeff: 0.5


datapool:
  id: commongen
  args:
    concept_end_token: '.'
    concept_separator_token: ' '
    prefix: "generate a sentence with: "


env:
  n_envs: 10
  args:
    max_prompt_length: 20
    max_episode_length: 20
    terminate_on_eos: True
    context_start_token: 0
    prompt_truncation_side: "right"


alg:
  id: ppo
  args:
    n_steps: 128
    batch_size: 64
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5
    ent_coef: 0.01
  kl_div:
    coeff: 0.01
    target_kl: 1.0
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: rajkumarrrk/t5-common-gen
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 50
        min_length: 5
        max_new_tokens: 20
    
train_evaluation:
  eval_batch_size: 50
  n_iters: 100
  eval_every: 5
  save_every: 20
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: cider
    - id: spice
    - id: diversity
      args: {}
  generation_kwargs:
    num_beams: 5
    min_length: 5
    max_new_tokens: 20

