tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: right
  pad_token_as_eos_token: False 

datapool:
  id: commongen
  args:
    concept_end_token: '.'
    concept_separator_token: ' '
    prefix: "generate a sentence with: "

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 8 
    logging_steps: 5000
    num_train_epochs: 4
    weight_decay: 0.01
    lr_scheduler_type: cosine
    learning_rate: 0.00001
    save_total_limit: 1
  model_type: seq2seq
  model_name: "t5-base"
  generation_kwargs:
    num_beams: 5
    min_length: 5
    max_new_tokens: 20
    post_processing_fn: null

train_evaluation:
  eval_batch_size: 100
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: cider
    - id: spice
    - id: diversity
      args: {}

