tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

datapool:
  id: iwslt2017en_de
  args:
    prompt_prefix: "translate English to German: "

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 64
    logging_steps: 1000
    num_train_epochs: 5
    weight_decay: 0.1
    lr_scheduler_type: "constant"
    learning_rate: 0.00001
    save_total_limit: 1
  model_type: seq2seq
  model_name: "t5-base"
  generation_kwargs:
    post_processing_fn: null
    num_beams: 4
    length_penalty: 0.6
    max_new_tokens: 128


train_evaluation:
  eval_batch_size: 50
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: bleu
      args: {}
    - id: sacre_bleu
      args:
        tokenize: "intl"
    - id: ter
      args: {}
    - id: chrf
      args: {}
    - id: diversity
      args: {}

